# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title/

# Setup
title:            'NickHorton.io'
tagline:          'Mathematician, Musician, Musclehead'
description:      'Personal notebook: mathematics, programming, and geek shit.'
url:              "http://0.0.0.0:4000"
baseurl:          "/"
paginate:         2

author:
  name:           'Nick Horton'
  url:            https://theironsamurai.com


# Sidebar Links

links:
  - title: About
    url: /about/
  - title: Tags
    url: /tags/
  - title: 'Other Blogs'
    url: /other-blogs/
  - title: Podcasts
    url: /podcasts/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/squatnemesis
